env:
  browser: true
  es6: true
extends:
  - react-app
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  no-tabs:
    - off
  react/jsx-props-no-spreading:
    - off
  react/jsx-filename-extension:
    - 1
    - extensions:
        - ".js"
        - ".jsx"
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
